### PR TITLE
Various scalar and type analysis backports

### PR DESCRIPTION
**Pull request by wsmoses**

### CODE REVIEW

**Comment by vchuravy** [comment]
Slightly worried about the 1.7 failures

**Comment by wsmoses** [comment]
> Slightly worried about the 1.7 failures

Agreed, but that's a nondeterminstic failure unrelated to this PR.

**Comment by vchuravy** [comment]
```
ulia: /opt/x86_64-linux-gnu/x86_64-linux-gnu/sys-root/usr/local/include/llvm/ADT/DenseMap.h:1247: bool llvm::operator==(const llvm::DenseMapIterator<llvm::ValueMapCallbackVH<const llvm::Value*, InvertedPointerVH, llvm::ValueMapConfig<const llvm::Value*, llvm::sys::SmartMutex<false> > >, InvertedPointerVH, llvm::DenseMapInfo<llvm::ValueMapCallbackVH<const llvm::Value*, InvertedPointerVH, llvm::ValueMapConfig<const llvm::Value*, llvm::sys::SmartMutex<false> > > >, llvm::detail::DenseMapPair<llvm::ValueMapCallbackVH<const llvm::Value*, InvertedPointerVH, llvm::ValueMapConfig<const llvm::Value*, llvm::sys::SmartMutex<false> > >, InvertedPointerVH>, false>&, const llvm::DenseMapIterator<llvm::ValueMapCallbackVH<const llvm::Value*, InvertedPointerVH, llvm::ValueMapConfig<const llvm::Value*, llvm::sys::SmartMutex<false> > >, InvertedPointerVH, llvm::DenseMapInfo<llvm::ValueMapCallbackVH<const llvm::Value*, InvertedPointerVH, llvm::ValueMapConfig<const llvm::Value*, llvm::sys::SmartMutex<false> > > >, llvm::detail::DenseMapPair<llvm::ValueMapCallbackVH<const llvm::Value*, InvertedPointerVH, llvm::ValueMapConfig<const llvm::Value*, llvm::sys::SmartMutex<false> > >, InvertedPointerVH>, false>&): Assertion `(!LHS.Ptr || LHS.isHandleInSync()) && "handle not in sync!"' failed.

signal (6): Aborted
in expression starting at /home/runner/work/Enzyme.jl/Enzyme.jl/test/threads.jl:37
gsignal at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
abort at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
unknown function (ip: 0x7fede7b2f728)
__assert_fail at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
operator== at /opt/x86_64-linux-gnu/x86_64-linux-gnu/sys-root/usr/local/include/llvm/ADT/DenseMap.h:1247
operator!= at /opt/x86_64-linux-gnu/x86_64-linux-gnu/sys-root/usr/local/include/llvm/ADT/DenseMap.h:1256 [inlined]
operator!= at /opt/x86_64-linux-gnu/x86_64-linux-gnu/sys-root/usr/local/include/llvm/IR/ValueMap.h:366 [inlined]
visitCallInst at /workspace/srcdir/Enzyme/enzyme/Enzyme/AdjointGenerator.h:8431
delegateCallInst at /opt/x86_64-linux-gnu/x86_64-linux-gnu/sys-root/usr/local/include/llvm/IR/InstVisitor.h:299 [inlined]
visitCall at /opt/x86_64-linux-gnu/x86_64-linux-gnu/sys-root/usr/local/include/llvm/IR/Instruction.def:209 [inlined]
visit at /opt/x86_64-linux-gnu/x86_64-linux-gnu/sys-root/usr/local/include/llvm/IR/Instruction.def:209
visit at /opt/x86_64-linux-gnu/x86_64-linux-gnu/sys-root/usr/local/include/llvm/IR/InstVisitor.h:112 [inlined]
CreateAugmentedPrimal at /workspace/srcdir/Enzyme/enzyme/Enzyme/EnzymeLogic.cpp:2017
EnzymeCreateAugmentedPrimal at /workspace/srcdir/Enzyme/enzyme/Enzyme/CApi.cpp:473
EnzymeCreateAugmentedPrimal at /home/runner/work/Enzyme.jl/Enzyme.jl/src/api.jl:146
enzyme! at /home/runner/work/Enzyme.jl/Enzyme.jl/src/compiler.jl:2600
unknown function (ip: 0x7fedb78d0d11)
_jl_invoke at /buildworker/worker/package_linux64/build/src/gf.c:2228 [inlined]
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2429
#codegen#71 at /home/runner/work/Enzyme.jl/Enzyme.jl/src/compiler.jl:3325
codegen##kw at /home/runner/work/Enzyme.jl/Enzyme.jl/src/compiler.jl:3104 [inlined]
_thunk at /home/runner/work/Enzyme.jl/Enzyme.jl/src/compiler.jl:3690
unknown function (ip: 0x7fedb78ca6ad)
_jl_invoke at /buildworker/worker/package_linux64/build/src/gf.c:2228 [inlined]
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2429
cached_compilation at /home/runner/.julia/packages/GPUCompiler/1FdJy/src/cache.jl:90
thunk at /home/runner/work/Enzyme.jl/Enzyme.jl/src/compiler.jl:3743
unknown function (ip: 0x7fedb78b9e90)
_jl_invoke at /buildworker/worker/package_linux64/build/src/gf.c:2228 [inlined]
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2429
unknown function (ip: 0x7fedcc0081a4)
unknown function (ip: 0x7fedcc00ccdd)
Allocations: 169683177 (Pool: 169594683; Big: 88494); GC: 122
Threads: Test Failed at /home/runner/work/Enzyme.jl/Enzyme.jl/test/runtests.jl:362
``` 

In the assertions tests

**Comment by vchuravy** [comment]
And threads is now:

```
dvanced Threads 1: Error During Test at /home/runner/work/Enzyme.jl/Enzyme.jl/test/threads.jl:37
  Got exception outside of a @test
  TaskFailedException
  
      nested task error: MethodError: no method matching (::Enzyme.Compiler.var"#fwd#38"{Vector{Ptr{Nothing}}, Enzyme.Compiler.AugmentedForwardThunk{var"#56#threadsfor_fun#9"{var"#56#threadsfor_fun#7#10"{Vector{Float64}, UnitRange{Int64}}}, Const{Nothing}, Tuple{}, var"#56#threadsfor_fun#9"{var"#56#threadsfor_fun#7#10"{Vector{Float64}, UnitRange{Int64}}}}})(::Int64)
      Closest candidates are:
        (::Enzyme.Compiler.var"#fwd#38")() at ~/work/Enzyme.jl/Enzyme.jl/src/compiler.jl:1228
      Stacktrace:
       [1] (::Base.Threads.var"#1#2"{Enzyme.Compiler.var"#fwd#38"{Vector{Ptr{Nothing}}, Enzyme.Compiler.AugmentedForwardThunk{var"#56#threadsfor_fun#9"{var"#56#threadsfor_fun#7#10"{Vector{Float64}, UnitRange{Int64}}}, Const{Nothing}, Tuple{}, var"#56#threadsfor_fun#9"{var"#56#threadsfor_fun#7#10"{Vector{Float64}, UnitRange{Int64}}}}}, Int64})()
         @ Base.Threads ./threadingconstructs.jl:30
```

on 1.8

**Comment by wsmoses** [comment]
Both of those are the current behavior of main, not related to this PR: https://github.com/EnzymeAD/Enzyme.jl/runs/6200492876?check_suite_focus=true

**Pull request merged**
