### PR TITLE
disable broken test on 1.8

### PR DESCRIPTION
**Pull request by vchuravy**
@wsmoses can you take a look at `threadsfor_fwd`? `vals` is not defined and I am unsure what you wanted to write there

### CODE REVIEW

**Comment by wsmoses** [comment]
This should be fixed in https://github.com/EnzymeAD/Enzyme.jl/pull/299 once that lands (eg once the GC bug is tracked down and fixed)

**Comment by vchuravy** [comment]
> (eg once the GC bug is tracked down and fixed)

Are the fixes separable? Also can you post a MWE for the GC bug?

**Comment by wsmoses** [comment]
Oh sorry, threadsfor_fwd should be fixed by https://github.com/EnzymeAD/Enzyme.jl/pull/299, this is distinct. Going to look at this right now to see if there's an easy fix.

**Comment by wsmoses** [comment]
Subsumed by https://github.com/EnzymeAD/Enzyme.jl/pull/335

**Pull request closed without merging**
