### PR TITLE
Fixup more than simple jacobian

### PR DESCRIPTION
**Pull request by wsmoses**

### CODE REVIEW

**Comment by wsmoses** [comment]
@swilliamson7 does this fix your jacobian case?

**Comment by swilliamson7** [comment]
> @swilliamson7 does this fix your jacobian case?

What the variable `n_out_val` mean exactly? It looks like I need to provide it.
```julia
julia> grad = jacobian(Reverse, compute_jacobian, S)
ERROR: MethodError: no method matching jacobian(::ReverseMode{false, FFIABI, false, false}, ::typeof(compute_jacobian), ::ShallowWaters.ModelSetup{Float32, Float32})

Closest candidates are:
  jacobian(::ReverseMode{ReturnPrimal, RABI, ErrIfFuncWritten}, ::F, ::X, ::Val{n_out_val}, ::Val{1}) where {F, X, n_out_val, ReturnPrimal, RABI<:EnzymeCore.ABI, ErrIfFuncWritten}
   @ Enzyme ~/.julia/packages/Enzyme/afdHl/src/Enzyme.jl:1302
  jacobian(::ReverseMode{ReturnPrimal, RABI, ErrIfFuncWritten}, ::F, ::X, ::Val{n_out_val}) where {F, X, n_out_val, ReturnPrimal, RABI<:EnzymeCore.ABI, ErrIfFuncWritten}
   @ Enzyme ~/.julia/packages/Enzyme/afdHl/src/Enzyme.jl:1302
  jacobian(::ReverseMode{ReturnPrimal, RABI, ErrIfFuncWritten}, ::F, ::X, ::Val{n_out_val}, ::Val{chunk}) where {F, X, chunk, n_out_val, ReturnPrimal, RABI<:EnzymeCore.ABI, ErrIfFuncWritten}
   @ Enzyme ~/.julia/packages/Enzyme/afdHl/src/Enzyme.jl:1253
  ...

Stacktrace:
 [1] top-level scope
   @ REPL[8]:1

```

**Comment by wsmoses** [comment]
it's the number of outputs

**Comment by swilliamson7** [comment]
If `f` doesn't necessarily return an array but rather a structure, what would I put? Or should I define `f` to return an array (say my state variable)?

**Comment by wsmoses** [comment]
@swilliamson7 just pushed a version which computes n_outs for you.

Currently reverse mode jacobian allows any input type, but requires an array output type.
Currently forward mode jacobian allows any output type, but requires an array or scalar input type.

**Comment by swilliamson7** [comment]
> @swilliamson7 just pushed a version which computes n_outs for you.
> 
> Currently reverse mode jacobian allows any input type, but requires an array output type. Currently forward mode jacobian allows any output type, but requires an array or scalar input type.

I saw! That was speedy lol, it doesn't seem like I can test it yet, or at least updating Enzyme doesn't bring any changes. I'm guessing I need to wait for the checks to pass or something?

**Comment by wsmoses** [comment]
@swilliamson7 it was just merged to main, so you now should be able to just do add Enzyme#main

**Comment by swilliamson7** [comment]
I got a fun blank-ish error,
```julia
julia> grad = jacobian(Reverse, compute_jacobian, S)
ERROR: MethodError: no method matching (ReverseMode{false, FFIABI, false})()
Stacktrace:
 [1] jacobian(::ReverseMode{false, FFIABI, false, false}, f::typeof(compute_jacobian), x::ShallowWaters.ModelSetup{Float32, Float32})
   @ Enzyme ~/.julia/packages/Enzyme/BkuKz/src/Enzyme.jl:1500
 [2] top-level scope
   @ REPL[13]:1
```

**Pull request merged**
