### PR TITLE
Add type error and array fix

### PR DESCRIPTION
**Pull request by wsmoses**

### CODE REVIEW

**Comment by vchuravy** [comment]
Hm on 1.8 we still see:

```
broadcast: Error During Test at /home/runner/work/Enzyme.jl/Enzyme.jl/test/runtests.jl:572
  Got exception outside of a @test
  Enzyme: Unknown concrete type in arraycopy_common
Test Summary: | Error  Total  Time
broadcast     |     1      1  7.9s
```

in CI

**Review by vchuravy — APPROVED** [review]
Wonderful, a better error for this is fantastic

**Comment by wsmoses** [comment]
So in particular this new error message creates a nice julia error for https://github.com/EnzymeAD/Enzyme.jl/issues/315 rather than the LLVM level assertion.

**Comment by vchuravy** [comment]
Ah it wasn't clear if this was intended to fix that error :)

**Pull request merged**
