### PR TITLE
Fix higher order codegen

### PR DESCRIPTION
**Pull request by wsmoses**

### CODE REVIEW

**Comment by vchuravy** [comment]
What's the GPU story here?

**Comment by wsmoses** [comment]
So the follow up there is basically to also have a similar handler that looks for deferred_(id) and we'll just run gpucompiler codegen there and inline the module similarly to here where we do the mapping variant from the pointer

**Comment by vchuravy** [comment]
I want to remove the `deferred_id` buisness from GPUCompiler so that we can actually precompile GPU kernels,
and I am not keen on maintaining two code-paths.

**Comment by wsmoses** [comment]
Hm how is pre compilation blocked?

but in any case yeah this PR primarily just fixes the “Enzyme.autodiff is the outermost compiler job” context

**Comment by wsmoses** [comment]
More thought/design is merited for when that is not the case

**Comment by vchuravy** [comment]
So this PR is the proposed new API for deferred compilation in GPUCompiler https://github.com/JuliaGPU/GPUCompiler.jl/pull/582 this is without any changes for Enzyme.

The rest of the stack is one possible way to add the necessary bits and bobs to make it Enzyme compatible.
Generally speaking, the rule for precompilation is "you shan't depend on runtime data"  so pointers or incrementing counters are out.

**Comment by vchuravy** [comment]
> Hm how is pre compilation blocked?

We will serialize a Julia CodeInfo that contains a magical pointer/id? That is then used for a dictionary that only exists during the runtime of a particular code.

**Comment by wsmoses** [comment]
hm yeah fair enough. 

In any case even if not a final resolution, would you be opposed to merging?

This net deletes code (including getting rid of a lot of runtime pointers) and removes the autodiff_deferred upgrade in absint, and thus fixes issues like https://github.com/EnzymeAD/Enzyme.jl/issues/2147

**Comment by wsmoses** [comment]
[to be clear we would still need to follow up/continue here, but it also at least unblocks the CPU side higher order stuff]

**Review by vchuravy — APPROVED** [review]

**Pull request merged**
