### PR TITLE
Bug Fix and use of new GPUCompiler persistent caching (8x improvement to loading time)

### PR DESCRIPTION
**Pull request by collinwarner**
Add functionality of GPUCompiler  https://github.com/JuliaGPU/GPUCompiler.jl/pull/425. Sees 8x improvement of cached loading times of the enzyme package.

Additionally latent bug found and fixed related to precompilation of Enzyme functions

### CODE REVIEW

**Comment by collinwarner** [comment]
image

**Comment by collinwarner** [comment]
Bug Found:

The following script will error out with a segfault in the current Enzyme implementation. This occurs because the generated functions for thunk and deferred_codegen do no retrigger GPUCompiler and instead use stale values. Simply dropping the generated tag fixes the segfault but we are no longer able to look up unique method instances as the returned world ages are incorrect. Instead we should switch to using GPUCompiler.methodinstance directly dropping the need to filter on world ages.



```
module EnzymeTest                                                               
using Enzyme                                                                    
                                                                                
f1(x) = x*x                                                                     
                                                                                
@show autodiff(Reverse, f1, Active(1.0))                                        
                                                                                
                                                                                
function __init__()                                                             
    @show autodiff(Reverse, f1, Active(1.0))                                    
end                                                                             
                                                                                
end # module EnzymeTest 
```

**Comment by vchuravy** [comment]
Can you split that last change out into a new PR?

**Comment by collinwarner** [comment]
Changing to new PR, cleaning

**Pull request closed without merging**
