### PR TITLE
Fix type escaping in `@import_frule`, `@import_rrule`

### PR DESCRIPTION
**Pull request by mofeing**
While trying to import some ChainRules from a package, I got the following error:

```julia
julia> using Enzyme, OMEinsum

julia> Enzyme.@import_rrule(typeof(einsum), OMEinsum.EinCode, Any, Any)
UndefVarError: `OMEinsum` not defined

Stacktrace:
 [1] macro expansion
   @ ~/.julia/packages/Enzyme/srACB/ext/EnzymeChainRulesCoreExt.jl:181 [inlined]
 [2] top-level scope
   @ ~/Developer/k-local-gradient-descent/notebooks/enzyme-omeinsum-from-chainrules.ipynb:1
```

By expanding the macro, I saw the the type annotations where not correctly escaped. For example, for `augmented_primal` we get
```
... augmented_primal(...) where {... var"#378#AN_1" <: Enzyme.Annotation{<:(Enzyme.OMEinsum).EinCode}, var"#379#AN_2" <: Enzyme.Annotation{<:Enzyme.Any}, var"#380#AN_3" <: Enzyme.Annotation{<:Enzyme.Any}}
```

Check out that `Enzyme.OMEinsum` and `Enzyme.Any` are wrong.

I haven't checked it out but this PR should fix it.

### CODE REVIEW

**Comment by wsmoses** [comment]
If possible can you add a test?

**Comment by mofeing** [comment]
Added! It tests against a `MockType` in a `MockModule`.

**Review by wsmoses — APPROVED** [review]

**Comment by wsmoses** [comment]
@mofeing this fails CI

**Comment by mofeing** [comment]
Forgot to add methods for `fdiff` and `rdiff`. Should be fixed now.

**Comment by mofeing** [comment]
I fixed all errors in the tests except one: The rrule test of `MockType`.

The pullback in `rrule` defined for `mock_function` should return a number
```julia
function ChainRulesCore.rrule(::typeof(MockModule.mock_function), x)
    y = MockModule.mock_function(x)
    return y, ȳ -> 2 * ȳ
end
```

But it seems like `Enzyme` is returning a `MockType`. Is this because we are annotating the return activity to be `Active`?

```julia
rdiff(f, x::MockModule.MockType) = autodiff(Reverse, f, Active, Active(x))[1][1]

Enzyme.@import_rrule typeof(MockModule.mock_function) MockModule.MockType
@test rdiff(MockModule.mock_function, MockModule.MockType(1f0)) === 2f0

...

import_rrule: Test Failed at /Users/mofeing/Developer/Enzyme.jl/test/ext/chainrulescore.jl:117
  Expression: rdiff(MockModule.mock_function, MockModule.MockType(1.0f0)) === 2.0f0
   Evaluated: Main.MockModule.MockType(2.0f0) === 2.0f0
```

**Comment by wsmoses** [comment]
@mofeing CI still fails "import_rrule: Test Failed at /home/runner/work/Enzyme.jl/Enzyme.jl/test/ext/chainrulescore.jl:117
  Expression: rdiff(MockModule.mock_function, MockModule.MockType(1.0f0)) === 2.0f0
   Evaluated: Main.MockModule.MockType(2.0f0) === 2.0f0
"

**Comment by wsmoses** [comment]
and no, for active vals, Enzyme returns a value of the same type (whatever it is)

**Comment by mofeing** [comment]
Okay, fixed now.

**Pull request merged**
