### PR TITLE
Test that exceptions are thrown

### PR DESCRIPTION
**Pull request by vchuravy**
@wsmoses you assume to much.

```
julia> Enzyme.Compiler.enzyme_code_llvm(f_simple_exc, Const, Tuple{Duplicated{Vector{Float64}}, Const{Int}})
; Function Attrs: alwaysinline
define void @diffejulia_f_simple_exc_2215.inner.5wrap({}* %0, {}* %1, i64 %2) #5 {
entry:
  %gcframe2 = alloca [3 x {}*], align 16
  %gcframe2.sub = getelementptr inbounds [3 x {}*], [3 x {}*]* %gcframe2, i64 0, i64 0
  %3 = bitcast [3 x {}*]* %gcframe2 to i8*
  call void @llvm.memset.p0i8.i32(i8* nonnull align 16 dereferenceable(24) %3, i8 0, i32 24, i1 false)
  %thread_ptr = call i8* asm "movq %fs:0, $0", "=r"() #7
  %ppgcstack_i8 = getelementptr i8, i8* %thread_ptr, i64 -8
  %ppgcstack = bitcast i8* %ppgcstack_i8 to {}****
  %pgcstack = load {}***, {}**** %ppgcstack, align 8
;  @ REPL[2] within `f_simple_exc` @ REPL[2]:1
; ┌ @ array.jl:861 within `getindex`
   %4 = bitcast [3 x {}*]* %gcframe2 to i64*
   store i64 4, i64* %4, align 16
   %5 = getelementptr inbounds [3 x {}*], [3 x {}*]* %gcframe2, i64 0, i64 1
   %6 = bitcast {}** %5 to {}***
   %7 = load {}**, {}*** %pgcstack, align 8
   store {}** %7, {}*** %6, align 8
   %8 = bitcast {}*** %pgcstack to {}***
   store {}** %gcframe2.sub, {}*** %8, align 8
   %9 = add i64 %2, -1
   %10 = bitcast {}* %0 to { i8*, i64, i16, i16, i32 }*
   %11 = getelementptr inbounds { i8*, i64, i16, i16, i32 }, { i8*, i64, i16, i16, i32 }* %10, i64 0, i32 1
   %12 = load i64, i64* %11, align 8
   %13 = icmp ult i64 %9, %12
   call void @llvm.assume(i1 %13)
   %14 = bitcast {}* %0 to double**
   %15 = load double*, double** %14, align 16
   %16 = getelementptr inbounds double, double* %15, i64 %9
   %17 = load double, double* %16, align 8
; └
  %ptls_field.i3.i = getelementptr inbounds {}**, {}*** %pgcstack, i64 2305843009213693954
  %18 = bitcast {}*** %ptls_field.i3.i to i8**
  %ptls_load.i45.i = load i8*, i8** %18, align 8
  %19 = call noalias nonnull {}* @jl_gc_pool_alloc(i8* %ptls_load.i45.i, i32 1392, i32 16) #8
  %20 = bitcast {}* %19 to i64*
  %21 = getelementptr inbounds i64, i64* %20, i64 -1
  store atomic i64 140178320221600, i64* %21 unordered, align 8
  %22 = bitcast {}* %19 to double*
  store double %17, double* %22, align 8
  %23 = getelementptr inbounds [3 x {}*], [3 x {}*]* %gcframe2, i64 0, i64 2
  store {}* %19, {}** %23, align 16
  call void inttoptr (i64 140178635388480 to void ({}*)*)({}* nonnull %19) #9
  call void inttoptr (i64 140178635388480 to void ({}*)*)({}* nonnull %19)
  %24 = load {}*, {}** %5, align 8
  %25 = bitcast {}*** %pgcstack to {}**
  store {}* %24, {}** %25, align 8
  ret void
}
```

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
I'm still getting some Enzyme segfaults. Does this solve it? Hard to make minimal, but:

```julia
using DiffEqFlux, OrdinaryDiffEq, Flux, DiffEqSensitivity
using Optim, Plots, 
using Random, Zygote
using ForwardDiff, 


function SEAIR!(du, u, p, t)
    S, E, A, I, R = u
    β, α, σ, γ = p

    du[1] = -β * S * (I + A)
    du[2] = β * S * (I + A) - α * E
    du[3] = α * E - σ * A
    du[4] = σ * A - γ * I
    du[5] = γ * I

end

#p = [0.85, 0.3, 0.2, 0.1]  # Note: some parameters work & others give error message
p = [0.417, 0.3, 0.5, 0.1] # Error Message: "Dimension Mismatch"

S0 = 1.0
u0 = [S0 * 0.97, S0 * 0.01, S0 * 0.01, S0 * 0.01, 0.0]
tspan = (0.0, 60.0)
tsteps = 0.0:1.0:60.0

prob_ode = ODEProblem(SEAIR!, u0, tspan, p)

sol_ode = solve(prob_ode, Tsit5(), saveat = tsteps)  #note: Tsit5 is a non-stiff ODE solver

ode_data = hcat([sol_ode[:, i] for i in 1:size(sol_ode, 2)]...)

######DEFINE THE UDE##########

global β, α1, σ, γ = [0.417, 0.3, 0.5, 0.1]  #


function SEAIR_ude!(du, u, p, t)
    global β, α1, σ, γ
    S, E, A, I, R = u

    ucollect = [u[1]; u[2]; u[3]; u[4]; u[5]]
    NN1 = abs(ann(ucollect, p[1:141])[1])

    #println(NN1)

    du[1] = -β * S * (I + A)
    du[2] = β * S * (I + A) - NN1 * E
    du[3] = α1 * E - σ * A
    du[4] = σ * A - γ * I
    du[5] = γ * I
end

# Initial condition
u0 = [S0 * 0.97, S0 * 0.01, S0 * 0.01, S0 * 0.01, 0.0]

tspan = (0.0, 60.0)
tsteps = 0.0:1.0:60.0


Random.seed!(2)  #experiment with random seed. previously used 2.
ann = FastChain(FastDense(5, 20, relu), FastDense(20, 1))
p0 = initial_params(ann)
p1 = zeros(141)
p1[141] = 0.35

# Setup the ODE problem, then solve
prob_ude = ODEProblem(SEAIR_ude!, u0, tspan, p1)
#Array(concrete_solve(prob_ude,Tsit5(),u0,p1,saveat = 2.0))

sol_ude = solve(prob_ude, Tsit5(), saveat = tsteps)  #note: Tsit5 is a non-stiff ODE solver

function train_neuralsir(steps, a, b, γ)
    θ = p1

    predict(p) = Array(solve(prob_ude, Tsit5(), p = p, saveat = tsteps,
        sensalg = InterpolatingAdjoint(autojacvec = ReverseDiffVJP(true))))

    loss(p) = sum(abs2, ode_data .- predict(p))

    trainlosses = [loss(p1); zeros(steps)]

    weights = [p1'; zeros(steps, length(p1))]

    for t in 1:steps
        ##########DEFINE########################
        beta = 0.9
        λ = 1e-8
        precond = zeros(length(θ))

        ################GRADIENT CALCULATIONS
        #x,lambda = Flux.Zygote.pullback(loss,θ)
        #∇L  = first(lambda(1))
        ∇L = Zygote.gradient(loss, θ)[1]

        #∇L= Flux.Zygote.gradient(loss, θ)[1]
        #ϵ = 0.0001
        ϵ = a * (b + t)^-γ

        ###############PRECONDITIONING#####################
        if t == 1
            precond[:] = ∇L .* ∇L
        else
            precond *= beta
            precond += (1 - beta) * (∇L .* ∇L)
        end
        #m = λ .+ sqrt.(precond/((1-(beta)^t)))
        m = λ .+ sqrt.(precond)

        ###############DESCENT###############################
        for i in 1:length(∇L)
            noise = ϵ * randn()
            #θ[i] = θ[i] - (0.5*ϵ*∇L[i] +  noise)
            θ[i] = θ[i] - (0.5 * ϵ * ∇L[i] / m[i] + noise)
        end

        #################BOOKKEEPING############################
        weights[t+1, :] = p1
        trainlosses[t+1] = loss(p1)
        println(loss(p1))
    end
    print("Final loss is $(trainlosses[end])")

    trainlosses, weights
end


results = train_neuralsir(100, 0.0001, 0.85, 0.01)
```

**Comment by wsmoses** [comment]
No @ChrisRackauckas your error is unrelated. This is a bug from GPUCompiler where throwing an error in the original code may not result in the same error being thrown when autodiff'd. So unless your original code is broken, this isn't relevant.

**Comment by vchuravy** [comment]
Can you post the stacktrace to a new issue?

**Comment by vchuravy** [comment]
@wsmoses since you asked about the original error:

```
julia> autodiff(f_simple_exc, Duplicated(y, f_x), 0)

ERROR: Enzyme compilation failed with: cannot find shadow for void ({} addrspace(10)*)* inttoptr (i64 140199560562333 to void ({} addrspace(10)*)*)
Stacktrace:
  [1] julia_error(cstr::Cstring)
    @ Enzyme.Compiler ~/.julia/packages/Enzyme/HGmm9/src/compiler.jl:2030
  [2] EnzymeCreatePrimalAndGradient(logic::Enzyme.Logic, todiff::LLVM.Function, retType::Enzyme.API.CDIFFE_TYPE, constant_args::Vector{Enzyme.API.CDIFFE_TYPE}, TA::Enzyme.TypeAnalysis, returnValue::Bool, dretUsed::Bool, mode::Enzyme.API.CDerivativeMode, width::Int64, additionalArg::Ptr{Nothing}, typeInfo::Enzyme.FnTypeInfo, uncacheable_args::Vector{Bool}, augmented::Ptr{Nothing}, atomicAdd::Bool)
    @ Enzyme.API ~/.julia/packages/Enzyme/HGmm9/src/api.jl:108
  [3] enzyme!(job::GPUCompiler.CompilerJob{Enzyme.Compiler.EnzymeTarget, Enzyme.Compiler.EnzymeCompilerParams, GPUCompiler.FunctionSpec{typeof(f_simple_exc), Tuple{Vector{Float64}, Int64}}}, mod::LLVM.Module, primalf::LLVM.Function, adjoint::GPUCompiler.FunctionSpec{typeof(f_simple_exc), Tuple{Duplicated{Vector{Float64}}, Const{Int64}}}, mode::Enzyme.API.CDerivativeMode, parallel::Bool, actualRetType::Type, dupClosure::Bool, wrap::Bool)
    @ Enzyme.Compiler ~/.julia/packages/Enzyme/HGmm9/src/compiler.jl:2592
  [4] codegen(output::Symbol, job::GPUCompiler.CompilerJob{Enzyme.Compiler.EnzymeTarget, Enzyme.Compiler.EnzymeCompilerParams, GPUCompiler.FunctionSpec{typeof(f_simple_exc), Tuple{Vector{Float64}, Int64}}}; libraries::Bool, deferred_codegen::Bool, optimize::Bool, ctx::LLVM.Context, strip::Bool, validate::Bool, only_entry::Bool, parent_job::Nothing)
    @ Enzyme.Compiler ~/.julia/packages/Enzyme/HGmm9/src/compiler.jl:3289
  [5] _thunk(job::GPUCompiler.CompilerJob{Enzyme.Compiler.EnzymeTarget, Enzyme.Compiler.EnzymeCompilerParams, GPUCompiler.FunctionSpec{typeof(f_simple_exc), Tuple{Vector{Float64}, Int64}}})
    @ Enzyme.Compiler ~/.julia/packages/Enzyme/HGmm9/src/compiler.jl:3654
  [6] cached_compilation(cache::Dict{UInt64, Any}, job::GPUCompiler.CompilerJob, compiler::typeof(Enzyme.Compiler._thunk), linker::typeof(Enzyme.Compiler._link))
    @ GPUCompiler ~/.julia/packages/GPUCompiler/1FdJy/src/cache.jl:90
  [7] thunk(f::typeof(f_simple_exc), df::Nothing, ::Type{Const{Nothing}}, tt::Type{Tuple{Duplicated{Vector{Float64}}, Const{Int64}}}, ::Val{Enzyme.API.DEM_ReverseModeCombined})
    @ Enzyme.Compiler ~/.julia/packages/Enzyme/HGmm9/src/compiler.jl:3707
  [8] autodiff
    @ ~/.julia/packages/Enzyme/HGmm9/src/Enzyme.jl:197 [inlined]
  [9] autodiff(::typeof(f_simple_exc), ::Duplicated{Vector{Float64}}, ::Int64)
    @ Enzyme ~/.julia/packages/Enzyme/HGmm9/src/Enzyme.jl:227
 [10] top-level scope
    @ REPL[7]:1
```

**Pull request merged**
