### PR TITLE
Update GPU CI

### PR DESCRIPTION
**Pull request by vchuravy**

### CODE REVIEW

**Comment by vchuravy** [comment]
@tgymnich can you look into the Metal failure?

**Comment by wsmoses** [comment]
@vchuravy I previously fixed the cause of the CUDA failire I could see (specifically not preserving nvcos for differentiating nvsin). Anything else failing is news to me.

**Comment by vchuravy** [comment]
Yeah we didn't ran Metal on CI.

**Comment by wsmoses** [comment]
Ah sorry that fix was here: https://github.com/EnzymeAD/Enzyme.jl/pull/967 but not merged since CI wouldn't start

**Pull request merged**
