### PR TITLE
Better active of vector error

### PR DESCRIPTION
**Pull request by wsmoses**
Fixes https://github.com/EnzymeAD/Enzyme.jl/issues/318

### CODE REVIEW

**Comment by simsurace** [comment]
I'm a little worried that this breaks `Active(::Tuple)` or `Active(::NamedTuple)`, which seemed to work fine as long as all values were e.g. `Float64`s. Shouldn't this keep working?

**Comment by wsmoses** [comment]
Yeah I concur, which is why this hasn't landed.

**Comment by wsmoses** [comment]
In reality we need a check that active only contains elements allocated inline/not vectors/ec

**Comment by simsurace** [comment]
I guess `StaticVectors` would be fine. Maybe some sort of recursive `ismutable`?

**Comment by wsmoses** [comment]
Superceeded elsewhere

**Pull request closed without merging**
